[build]
  command = "bash build.sh"
  functions = "functions"
  publish = "public" # Empty folder to prevent default static serving

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
