[build]
  command = "mkdir -p functions/api && cp main.py functions/api/api.py && cp file_parser.py functions/api/file_parser.py && cp credentials.txt functions/api/credentials.txt && cp -r static functions/api/static && pip install -t functions/api -r requirements.txt"
  functions = "functions"
  publish = "public" # Empty folder to prevent default static serving

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
